name: CMake

on: push

jobs:
  build_and_test_Taffo:
    # The CMake configure and build commands are platform-agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    container:
      image: docker.io/ledmington/taffo-deps:llvm18.1.8

    steps:

    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          git \
          gcc \
          g++ \
          ninja-build \
          python3 \
          python3-pip \
          python3-venv \
          protobuf-compiler \
          lsb-release \
          clang-format-19

    - name: Python Dependencies
      run: |
        cd ${GITHUB_WORKSPACE}
        python3 -m venv .venv
        . .venv/bin/activate
        pip install -r requirements.txt

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cd ${GITHUB_WORKSPACE}
        cmake -S ${GITHUB_WORKSPACE} -B ${GITHUB_WORKSPACE}/build -G Ninja \
          -CMAKE_C_COMPILER=gcc \
          -CMAKE_C_COMPILER=g++ \
          -DTAFFO_UNITTESTS=ON \
          -DLLVM_DIR="/opt/llvm-18"

    - name: Build
      # Build your program with the given configuration
      run: |
        cmake --build ${GITHUB_WORKSPACE}/build -j $(nproc) -- all
        cmake --build ${GITHUB_WORKSPACE}/build -- install

    - name: Test
      env:
        LD_LIBRARY_PATH: /opt/or-tools/lib:/opt/llvm-18/lib
      run: |
        cd ${GITHUB_WORKSPACE}
        . .venv/bin/activate
        ctest --test-dir ${GITHUB_WORKSPACE}/build -j $(nproc) --output-on-failure --timeout 3600
