name: CMake

on: push

jobs:
  build_and_test_Taffo:
    # The CMake configure and build commands are platform-agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    container:
      image: docker.io/ledmington/taffo-deps:llvm18.1.8

    steps:

    - name: Setup Python
      uses: actions/setup-python@v4.3.1

    - name: Pip
      run: pip install -r requirements.txt

    - name: Dependencies
      run: |
        sudo apt install protobuf-compiler
        sudo apt install -y lsb-release clang-format-19

    - uses: actions/checkout@v4

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DLLVM_DIR="/opt/llvm-18-d" -DCMAKE_PREFIX_PATH="/opt/or-tools"

    - name: Build
      # Build your program with the given configuration
      run: |
        cmake --build ${{github.workspace}}/build -j $(nproc) -- all
        cmake --build ${{github.workspace}}/build -- install

    - name: Test
      env:
        LD_LIBRARY_PATH: /opt/or-tools/lib:/opt/llvm-18-d/lib
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --test-dir ${{github.workspace}}/build -j $(nproc) --output-on-failure --timeout 3600
